name: Generate Allure Report

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin